# Site settings
title: Alper Şanlı 
description: CV Website
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alper Şanlı
user_description: 
user_title: 
email: alpersanli16@gmail.com
github_username: alpersanli

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']





plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# BLOG (varsa dursun)
paginate: 5
paginate_path: "/blog/page:num"

# SCRATCHPAD (casual chatty posts)
collections:
  scratchpad:
    output: true
    permalink: /scratchpad/:name/

# Optional: feed for scratchpad too (tek ortak feed yeterliyse bunu çıkar)
feed:
  collections:
    - posts
    - scratchpad

